import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import Providers from './providers';
import { Toaster } from '@/lib/components/ui/toaster';

const poppins = Poppins({
    subsets: ['latin'], // You can add more subsets if you want
    weight: ['300', '400', '500', '600', '700'], // Which weights you want to use
    variable: '--font-poppins', // 👈 This sets it as a CSS variable
    display: 'swap', // Better performance
});

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const queryClient = new QueryClient();

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${poppins.variable} antialiased font-poppins bg-white`}
            >
                <Providers>{children}</Providers>
                <Toaster />
            </body>
        </html>
    );
}
